import React, { useEffect } from "react";
import { useDispatch, useSelector } from "react-redux";
import Notebook from "thebe-core/dist/notebook";
import { RDisplay, RScope } from "./components";
import RDynamic from "./components/RDynamic";
import RVar from "./components/RVar";
import Output from "./Output";
import { AppDispatch, selectors } from "./store";
import actions, { fetchNotebook } from "./store/actions";
import "thebe-core/dist/index.css";
import JustMakePageLive from "./JustMakePageLive";
import RAction from "./components/RAction";

function MyArticle() {
  const dispatch = useDispatch<AppDispatch>();
  const notebookId = useSelector(selectors.compute.getActiveNotebookId);

  useEffect(() => {
    dispatch(fetchNotebook()).then((nb: Notebook) => {
      dispatch(actions.compute.setActiveNotebookId(nb.id));
    });
  }, []);

  return (
    <RScope name="page">
      <div style={{ position: "fixed", top: 0, left: 0, visibility: "hidden" }}>
        <RVar name="cond" value={0.01} format=".3f"></RVar>
        <RVar name="offset" value={100} format=".0f"></RVar>
      </div>
      <article className="centered">
        <JustMakePageLive notebookId={notebookId} />
        <h1>Difference between magnetic dipole and loop sources</h1>
        <p>
          In this example we look at the differences between an electric loop
          loop, which results in a magnetic source, and a magnetic dipole
          source.
        </p>
        <p>
          The derivation of the electromagnetic field in Hunziker et al. (2015)
          is for electric and magnetic point-dipole sources and receivers. The
          magnetic field due to a magnetic source ($mm$) is obtain from the
          electric field due to an electric source ($ee$) using the duality
          principle, given in their Equation (11),
        </p>

        {
          "$$\\hat{G}^{mm}_{pq}(\\mathbf{x}, \\mathbf{x'}, s, \\eta_{kr}, \\zeta_{ij}) = -\\hat{G}^{ee}_{pq}(\\mathbf{x}, \\mathbf{x'}, s, -\\zeta_{kr}, -\\eta_{ij}) \\, . \\qquad (1)$$"
        }
        <p>
          Without going into the details of the different parameters, we can
          focus on the difference between the and $ee$ fields for a homogeneous,
          isotropic fullspace by simplifying this further to
        </p>
        {
          "$$\\mathbf{G}^{mm}_\\text{dip-dip} = \\frac{\\eta}{\\zeta}\\mathbf{G}^{ee} \\quad\\xrightarrow{\\text{diff. approx}} \\quad \\frac{\\sigma}{\\mathrm{i}\\omega\\mu}\\mathbf{G}^{ee}_\\text{dip-dip} \\, . \\qquad (2)$$"
        }
        <p>
          Here, $\sigma$ is conductivity (S/m), $\omega=2\pi f$ is angular
          frequency (Hz), and is the magnetic permeability (H/m). So from
          Equation (2) we see that the $mm$ field differs from the field by a
          factor {"$\\sigma/(\\mathrm{i}\\omega\\mu)$"}.
        </p>
        <p>
          A magnetic dipole source has a moment of $I^mds$; however, a magnetic
          dipole source is basically never used in geophysics. Instead a loop of
          an electric wire is used, which generates a magnetic field. The moment
          generated by this loop is given by{" "}
          {"$I^m = \\mathrm{i}\\omega\\mu N A I^e$"}, where $A$ is the area of
          the loop (m:math:^2), and $N$ the number of turns of the loop. So the
          difference between a unit magnetic dipole and a unit loop ($A=1, N=1$)
          is the factor {"$\\mathrm{i}\\omega\\mu$"}, hence Equation (2) becomes
        </p>
        {
          "$$\\mathbf{G}^{mm}_\\text{loop-dip} = \\mathrm{i}\\omega\\mu\\mathbf{G}^{mm}_\\text{dip-dip} = \\sigma\\,\\mathbf{G}^{ee}_\\text{dip-dip} \\, . \\qquad (3)$$"
        }
        <p>
          This example shows this relation in the frequency domain, as well as
          for impulse, step-on, and step-off responses in the time domain.
        </p>
        <p>
          We can actually model an electric loop instead of adjusting the
          magnetic dipole solution to correspond to a loop source. This is shown
          in the second part of the notebook.
        </p>
        <p>
          <strong>References</strong>
          <ul>
            <li>
              Hunziker, J., J. Thorbecke, and E. Slob, 2015, The electromagnetic
              response in a layered vertical transverse isotropic medium: A new
              look at an old problem: Geophysics, 80(1), F1–F18; DOI:
              10.1190/geo2013-0411.1.
            </li>
          </ul>
        </p>
        <h2>Using the magnetic dipole solution</h2>
        <h3>Survey parameters</h3>
        <p>
          <ul>
            <li>
              Homogenous fullspace of $\sigma$ ={" "}
              <RDynamic
                bind="cond"
                min={0.005}
                max={0.1}
                step={0.005}
                format=".3f"
              ></RDynamic>{" "}
              S/m.
            </li>
            <li>Source at the origin, x-directed.</li>
            <li>
              Inline receiver with offset of{" "}
              <RDynamic
                bind="offset"
                min={10}
                max={500}
                step={10}
                format=".0f"
              ></RDynamic>
              m, x-directed.
            </li>
          </ul>
        </p>
        <h3>Computation using `empymod` & visualization</h3>
        <Output
          notebookId={notebookId}
          cellId="curvenote-cell-id-4"
          placeholder={<img src="figure1.png" alt="composite signal" />}
        />
        <p>
          The figure shows the main points of Equations (2) and (3):
          <ul>
            <li>
              The magnetic dipole-dipole response differs by a factor{" "}
              {"$\\sigma/(\\mathrm{i}\\omega\\mu)$"} from the electric
              dipole-dipole response. That means for the time-domain that the
              magnetic response looks more like the time derivative of the
              electric response (e.g., the magnetic impulse responses resembles
              the electric step-on response).
            </li>
            <li>
              The magnetic loop-dipole response differs only by $\sigma$ from
              the electric dipole-dipole response, hence a factor of{" "}
              <RDisplay bindToValue="cond" format=".3f"></RDisplay>.
            </li>
          </ul>
          The units of the response only depend on the receiver, what the
          receiver actually measures. So if we change the source from a dipole
          to a loop it does not change the units of the received responses.
        </p>
        <p></p>
      </article>
    </RScope>
  );
}

export default MyArticle;
